parameters:
- name: dockerTag
  displayName: Docker Tag (Required)
  type: string

trigger:
- none

pr:
- none

variables:
- group: kv-core-210713               # The name of the ado keyvault variable group.
- name:  objSuffix
  value: voteapp-220606-1000
- name:  rgNamePrd
  value: 'rg-prd-$(objSuffix)'
- name:  aksNamePrd
  value: 'aks-prd-nteu-$(objSuffix)'

jobs:

# Deploy voting app manifests to prd.
- job: 'k8sDeployPrd'
  displayName: 'K8s - Deploy (PRD)'
  condition: eq(variables['Build.SourceBranchName'], 'prd')
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - bash: |
      az login --service-principal -u $(KV-ARM-CLIENT-ID) -p $(KV-ARM-CLIENT-SECRET) --tenant $(KV-ARM-TENANT-ID)
      az aks get-credentials --resource-group $(rgNamePrd) --name $(aksNamePrd) --admin
    displayName: 'K8s - Deploy (PRD)'
    workingDirectory: 'k8s/'
