parameters:
- name: dockerTag
  displayName: Docker Tag (Required)
  type: string

trigger:
- none

pr:
- none

variables:
- group: kv-core-210713               # The name of the ado keyvault variable group.

- name:  mySqlFqdnPrd
  value: 'mysql-prd-nteu-voteapp-220606-1000.mysql.database.azure.com'
- name:  mySqlNamePrd
  value: 'mysql-prd-nteu-voteapp-220606-1000'
- name:  urlPrd
  value: 'prd.rhor3rz.com'

- name:  rgNamePrd
  value: 'rg-prd-$(objSuffix)'
- name:  aksNamePrd
  value: 'aks-prd-nteu-$(objSuffix)'

jobs:

# Deploy voting app manifests to prd.
- job: 'k8sDeployPrd'
  displayName: 'K8s - Deploy (PRD)'
  condition: eq(variables['Build.SourceBranchName'], 'prd')
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: templates/k8sDeploy.yml
    parameters:
      tag: ${{ parameters.dockerTag }}
      mySqlFqdn: $(mySqlFqdnPrd)
      mySqlName: $(mySqlNamePrd)
      url: $(urlPrd)
